# Generated by Django 5.0.1 on 2024-05-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NORMAL_USER', 'Normal User'), ('PREMIUM_USER', 'Premium User'), ('IT_ADMINISTRATOR', 'IT Administrator'), ('ROOT', 'Root')], default='NORMAL_USER', max_length=50),
        ),
    ]
