# Generated by Django 5.0.1 on 2024-07-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdiagram',
            name='user',
        ),
    ]
