# Generated by Django 5.0.1 on 2024-07-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0002_remove_classdiagram_user'),
        ('model_manager', '0002_create_model_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdiagram',
            name='model_id',
        ),
        migrations.AddField(
            model_name='classdiagram',
            name='model_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='model_manager.modelname'),
            preserve_default=False,
        ),
    ]
