# Generated by Django 5.0.1 on 2024-07-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0003_remove_classdiagram_model_id_classdiagram_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdiagram',
            old_name='model_name',
            new_name='model',
        ),
    ]
