# Generated by Django 5.0.1 on 2024-07-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0009_sequencediagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencediagram',
            name='alt_flows',
        ),
        migrations.RemoveField(
            model_name='sequencediagram',
            name='loops',
        ),
        migrations.RemoveField(
            model_name='sequencediagram',
            name='messages',
        ),
    ]
