# Generated by Django 5.0.1 on 2024-07-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0010_remove_sequencediagram_alt_flows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencediagram',
            name='feature',
            field=models.JSONField(),
        ),
    ]
