version: "3.8"

services:
  jenkins:
    build:
      context: . 
      dockerfile: Dockerfile 
    privileged: true
    user: root
    ports:
      - "8080:8080"
    environment:
      - JENKINS_ARGS=--prefix=/jenkins
      - JAVA_OPTS=-Xmx2048m -Xms1024m  # Adjust the JVM settings for Jenkins
    volumes:
      - "jenkins_home:/var/jenkins_home"
    mem_limit: 3500m  # Set memory limit to 3.5GB

  sonarqube:
    image: sonarqube:latest
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5433/sonar
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - sonarqube_data:/opt/sonarqube/data

  db:
    image: postgres:latest
    container_name: sonarqube_sql  
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    ports:
      - "5433:5432"
    volumes:
      - sonarqube_sql:/var/lib/postgresql/data  

volumes:
  jenkins_home:
  sonarqube_sql:  
  sonarqube_data:
