# Generated by Django 5.0.1 on 2024-06-22 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Job Status',
                'verbose_name_plural': 'Job Statuses',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
