# Generated by Django 5.0.1 on 2024-06-22 13:35
from django.db import migrations, IntegrityError

# Populate valid statuses into JobStatus table
def create_initial_job_statuses(apps, schema_editor):
    JobStatus = apps.get_model('jobs', 'JobStatus')
    statuses = [
        {"name": "Draft", "code": 0},
        {"name": "Queued", "code": 1},
        {"name": "Submitted", "code": 2},
        {"name": "Error Failed to Submit", "code": 3},
        {"name": "Processing", "code": 4},
        {"name": "Error Failed to Process", "code": 5},
        {"name": "Job Aborted", "code": 6},
        {"name": "Completed", "code": 7},
    ]
    for status in statuses:
        try:
            JobStatus.objects.create(**status)
        except IntegrityError:
            # If status already exists, skip it
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobstatus_alter_job_job_id'),
    ]

    operations = [
        migrations.RunPython(create_initial_job_statuses),
    ]