# Generated by Django 5.0.1 on 2024-06-25 14:47

from django.db import migrations, IntegrityError

def create_initial_job_statuses(apps, schema_editor):
    JobStatus = apps.get_model('jobs', 'JobStatus')
    statuses = [
        {"name": "Draft", "code": 1},
        {"name": "Queued", "code": 2},
        {"name": "Submitted", "code": 3},
        {"name": "Error Failed to Submit", "code": 4},
        {"name": "Processing", "code": 5},
        {"name": "Error Failed to Process", "code": 6},
        {"name": "Job Aborted", "code": 7},
        {"name": "Completed", "code": 8},
    ]
    for status in statuses:
        try:
            JobStatus.objects.create(**status)
        except IntegrityError as e:
            print(f"Failed to create status: {status}. Error: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobstatus_alter_job_job_id_alter_job_job_status'),
    ]

    operations = [
        migrations.RunPython(create_initial_job_statuses),
    ]