# Generated by Django 5.0.1 on 2024-06-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobstatus_create_jobstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobstatus'),
        ),
    ]
