# Generated by Django 5.0.1 on 2024-06-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_job_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_status_histories', to='jobs.jobstatus', to_field='code')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_status_histories', to='jobs.jobstatus', to_field='code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobs.job')),
                ('consumer', models.CharField(max_length=50)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobstatus', to_field='code')),
            ],
        ),
    ]
