# Generated by Django 5.0.1 on 2024-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobhistory_jobqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='reason',
            field=models.TextField(default='Status changed by user.', max_length=100),
        ),
    ]
