# Generated by Django 5.0.1 on 2024-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobhistory_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhistory',
            old_name='changed_timestamp',
            new_name='updated_timestamp',
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='consumer',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
