# Generated by Django 5.0.1 on 2024-07-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_rename_updated_timestamp_jobhistory_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_jobs', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
