# Generated by Django 5.0.1 on 2024-07-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_job_parent_id_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_parent_id',
            new_name='job_parent',
        ),
    ]
