# Generated by Django 5.0.1 on 2024-07-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_rename_job_parent_job_parent_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('user_story', 'User Story'), ('class_diagram', 'Class Diagram'), ('er_diagram', 'ER Diagram'), ('sequence_diagram', 'Sequence Diagram'), ('state_diagram', 'State Diagram')], max_length=50),
        ),
    ]
