# Generated by Django 5.0.1 on 2024-07-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobqueue',
            name='job_type',
            field=models.CharField(default='Class Diagram', max_length=50),
            preserve_default=False,
        ),
    ]
