# Generated by Django 5.0.1 on 2024-07-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_jobqueue_job_type'),
        ('model_manager', '0002_create_model_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='model_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model_manager.modelname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobqueue',
            name='model_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model_manager.modelname'),
            preserve_default=False,
        ),
    ]
