# Generated by Django 5.0.1 on 2024-07-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_rename_model_name_job_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobqueue',
            old_name='model_name',
            new_name='model',
        ),
    ]
