# Generated by Django 5.0.1 on 2024-07-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_remove_jobhistory_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='job_type',
            field=models.CharField(default='class_diagram', max_length=50),
            preserve_default=False,
        ),
    ]
