# Generated by Django 5.0.1 on 2024-07-14 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_jobhistory_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_status_histories', to='jobs.jobstatus', to_field='code'),
        ),
    ]
